### ISSUE TITLE
Suddenly not pulling payments. Getting the following message

### ISSUE THREAD

**Issue by Budrose** [XeroAPI/xero-php-oauth2-app#30]
from: 2021,02,01to: 2021,02,28Date >= DateTime(2021,02,01) and Date <= DateTime(2021,02,28)
Fatal error: Uncaught XeroAPI\XeroPHP\ApiException: [400] Client error: `GET https://api.xero.com/api.xro/2.0/Payments?where=Date%20%3E%3D%20DateTime%282021%2C02%2C01%29%20and%20Date%20%3C%3D%20DateTime%282021%2C02%2C28%29%20and%20PaymentType%3D%3D%22ACCRECPAYMENT%22` resulted in a `400 Bad Request` response: Your request is not filtering payments efficiently, given the extremely high volume for this organisation. Please check (truncated...) in C:\xampp\htdocs\xero-raglanOauth2\vendor\xeroapi\xero-php-oauth2\lib\Api\AccountingApi.php:42232 Stack trace: #0 C:\xampp\htdocs\xero-raglanOauth2\vendor\xeroapi\xero-php-oauth2\lib\Api\AccountingApi.php(42204): XeroAPI\XeroPHP\Api\AccountingApi->getPaymentsWithHttpInfo('652460cf-9738-4...', NULL, 'Date >= DateTim...', NULL, NULL) #1 C:\xampp\htdocs\xero-raglanOauth2\indexoauth2.php(190): XeroAPI\XeroPHP\Api\AccountingApi->getPayments('652460cf-9738-4...', NULL, 'Date >= DateTim...') #2 {main} thrown in C:\xampp\htdocs\xero-raglanOauth2\vendor\xeroapi\xero-php-oauth2\lib\Api\AccountingApi.php on line 42232

**Comment by RettBehrens** [comment]
In order to maintain stability and performance for everybody on the platform,  we’re introducing a high volume threshold to the Payment endpoint. This will impact the way your app interacts with organisations with more than a 100,000 payments.

To make sure that your app can still retrieve data from high volume organisations, you’ll need to change the way you’re calling the payment endpoint
Don’t request all payments in a single request (i.e. you must use paging)
Only use filter and order combinations that have been specifically optimised for use in high volume organisations (including when using paging). [More details here](https://developer.xero.com/documentation/api/efficient-data-retrieval).

Without these changes, Get payment requests to these organisations will result in a 400 error response.

The high volume threshold went into effect Jan 2021.

Please take a look at the [documentation](https://developer.xero.com/documentation/api/payments) on developer center, which outlines how you can use paging and optimise your filtering to ensure your requests are always successful.
 
If you have any further questions, please contact api@support.xero.com.
