### ISSUE TITLE
Please help with below. Getting very urgent

### ISSUE THREAD

**Issue by Budrose** [XeroAPI/xero-php-oauth2-app#31]
Hi I am a developer but in more client server type applications. I have been using a php xero framework to post transactions into xero. I have one client who I download transactions for and then write a report. I download invoices, payments, credits and overpayments. This has worked for the last couple of years. Suddenly this month, it won't get the payments . This is the error 'Your request is not filtering payments efficiently, given the extremely high volume for this organisation.' I have run the same code under other xero clients and it works fine. I would really appreciate any help you can give.

**Comment by RettBehrens** [comment]
In order to maintain stability and performance for everybody on the platform,  we’re introducing a high volume threshold to the Payment endpoint. This will impact the way your app interacts with organisations with more than a 100,000 payments.

To make sure that your app can still retrieve data from high volume organisations, you’ll need to change the way you’re calling the payment endpoint
Don’t request all payments in a single request (i.e. you must use paging)
Only use filter and order combinations that have been specifically optimised for use in high volume organisations (including when using paging). [More details here](https://developer.xero.com/documentation/api/efficient-data-retrieval).

Without these changes, Get payment requests to these organisations will result in a 400 error response.

The high volume threshold went into effect Jan 2021.

Please take a look at the [documentation](https://developer.xero.com/documentation/api/payments) on developer center, which outlines how you can use paging and optimise your filtering to ensure your requests are always successful.
 
If you have any further questions, please contact api@support.xero.com.

**Comment by Budrose** [comment]
Hi Rett. I am using a filter both on Transaction Type and Payment Date. The same code works absolutely fine on other clients but just have a problem on the one client.

**Comment by RettBehrens** [comment]
Please contact api@support.xero.com so they can investigate further and provide more specific feedback regarding your integration. They'll ask for either the Client ID and/or App ID, which you can find by viewing your app details in the [developer portal](https://developer.xero.com/myapps)
